version: '3.3'
services:
  spring:
    container_name: spring
    build:
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/devopsprojet?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    image: azizbenismail/kaddem:9
    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  angular-app:
    image: azizbenismail/kaddemangular:latest 
    container_name: angular-app
    ports:
      - "4200:80"  # Assurez-vous que les ports correspondent à ceux que vous utilisez dans votre application
    restart: always  # Optionnel : redémarrer toujours le conteneur en cas d'échec

volumes:
  db:
